// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFp7q8BirgXGMbCHt44oNATYz46Uctxmo',
    appId: '1:378734731856:web:aedb99f1d45229cff2e755',
    messagingSenderId: '378734731856',
    projectId: 'device-streaming-95a10d81',
    authDomain: 'device-streaming-95a10d81.firebaseapp.com',
    storageBucket: 'device-streaming-95a10d81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnWj_X4hBdbXpxa1X0nKL0wWkUBUFfUo',
    appId: '1:378734731856:android:3b92da7a68774e22f2e755',
    messagingSenderId: '378734731856',
    projectId: 'device-streaming-95a10d81',
    storageBucket: 'device-streaming-95a10d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq8QsOHEV6KwrHXNmdNaYEbMVJ9BjlOZo',
    appId: '1:378734731856:ios:0fb0ea22895a570ef2e755',
    messagingSenderId: '378734731856',
    projectId: 'device-streaming-95a10d81',
    storageBucket: 'device-streaming-95a10d81.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq8QsOHEV6KwrHXNmdNaYEbMVJ9BjlOZo',
    appId: '1:378734731856:ios:62df9beb25c74254f2e755',
    messagingSenderId: '378734731856',
    projectId: 'device-streaming-95a10d81',
    storageBucket: 'device-streaming-95a10d81.firebasestorage.app',
    iosBundleId: 'com.example.testNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFp7q8BirgXGMbCHt44oNATYz46Uctxmo',
    appId: '1:378734731856:web:99bdb2666c08948af2e755',
    messagingSenderId: '378734731856',
    projectId: 'device-streaming-95a10d81',
    authDomain: 'device-streaming-95a10d81.firebaseapp.com',
    storageBucket: 'device-streaming-95a10d81.firebasestorage.app',
  );

}